
import React from 'react';
import type { Achievement, StudentProfile } from '../types';
import { ActivityType } from '../types';
import { Avatar } from './Avatar';

interface PortfolioPDFLayoutProps {
    achievements: Achievement[];
    profile: StudentProfile;
}

const getIconForType = (type: ActivityType) => {
    // A simple text-based icon for PDF
    switch (type) {
        case ActivityType.Internship: return '💼';
        case ActivityType.Competition: return '🏆';
        case ActivityType.Certification: return '📜';
        case ActivityType.Conference: return '🎤';
        case ActivityType.Workshop: return '🛠️';
        case ActivityType.ClubActivity: return '👥';
        case ActivityType.CommunityService: return '❤️';
        case ActivityType.OnlineCourse: return '💻';
        default: return '⭐';
    }
};

export const PortfolioPDFLayout: React.FC<PortfolioPDFLayoutProps> = ({ achievements, profile }) => {
    return (
        <div className="p-12 font-sans bg-white text-gray-800">
            {/* Header */}
            <div className="flex items-center border-b-2 border-gray-200 pb-6 mb-8">
                <div className="flex-shrink-0 mr-6">
                    {profile.profilePictureUrl ? (
                         <img src={profile.profilePictureUrl} alt={profile.name} className="w-24 h-24 rounded-full object-cover" crossOrigin="anonymous" />
                    ) : (
                        <div className="w-24 h-24 rounded-full bg-violet-600 text-white flex items-center justify-center text-4xl font-bold">
                            <span>{profile.name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase()}</span>
                        </div>
                    )}
                </div>
                <div>
                    <h1 className="text-4xl font-bold">{profile.name}</h1>
                    <p className="text-md text-gray-500 mt-2">
                        {profile.email} | {profile.major} | {profile.institutionCode}
                    </p>
                </div>
            </div>

            {/* Achievements */}
            <div>
                <h2 className="text-xl font-bold text-violet-700 border-b border-gray-200 pb-2 mb-4">ACHIEVEMENTS</h2>
                <div className="space-y-5">
                    {achievements.map(ach => (
                        <div key={ach.id} className="flex items-start">
                            <div className="text-2xl mr-4 mt-1">{getIconForType(ach.type)}</div>
                            <div className="flex-1">
                                <div className="flex justify-between items-baseline">
                                    <h3 className="text-lg font-semibold">{ach.title}</h3>
                                    <p className="text-xs text-gray-500">{ach.date}</p>
                                </div>
                                <p className="text-xs font-medium text-violet-600 uppercase tracking-wider">{ach.type}</p>
                                <p className="mt-1 text-gray-600 text-sm">{ach.description}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
             <div className="text-center mt-12 text-xs text-gray-400">
                Generated by Pathfolio
            </div>
        </div>
    );
};
